### ISSUE TITLE
PHP Fehler 500er seit neue Version

### ISSUE THREAD

**Issue by csaeum** [designs2/codeowl_fw_foundation#12]
Ich bekomme bei einer Webseite von mir mit der neuen Version einen 500er. Laut Provider aufgrund das die CPU Zeit von 15 Sek überschritten ist.

Kann leider nicht mehr geben indem Paket. Mit der alten Version lief alles super.

**Comment by csaeum** [comment]
Ok es scheint noch ein anderes Problem zu geben. Ich habe mal ein neues C3.5 installiert sowie CodeOwl und das läuft es ohne Probleme.

Ich teste nochmal was und gebe bescheid.

**Comment by MoniqueHahnefeld** [comment]
Ein Timeout von 15 Sekunden ist wenig und dein Webhostingpaket ist sicherlich zu lahm. Das hat nichts mit der Erweiterung zu tun.
