### ISSUE TITLE
2.0.1 - angelegte scss bringt Fehler

### ISSUE THREAD

**Issue by jedoCodes** [designs2/codeowl_fw_foundation#24]
die scss, welche in der config erstellt wird zerlegt die Webseite mit einer FM "Internal Server Error". nehme ich diese Datei einfach aus dem layout ist alles wieder Okay..

ProgressBar funktioniert somit nicht

**Comment by MoniqueHahnefeld** [comment]
Hi,
the issue is caused maybe by what I describe here #29?

otherwise I developed the last 3 weeks and will upload the new version today with some other issues i found while I was working with the extension.

**Comment by jedoCodes** [comment]
das problem besteht aber weiterhin auch in der V2.0.2
